/**
 * Prisma Seed — 50+ Popular APIs
 * Run: npx prisma db seed
 */

import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const APIS = [
  // ======== PAYMENTS ========
  {
    slug: 'stripe',
    name: 'Stripe',
    description: 'The complete payments platform. Accept payments, send payouts, and manage your business online.',
    longDescription: 'Stripe is the gold standard for payment processing. Used by millions of businesses worldwide, it provides a complete suite of payment APIs including credit cards, ACH, and international payments.',
    category: 'payments',
    tags: ['payment', 'checkout', 'subscription', 'billing', 'fintech'],
    logoUrl: 'https://logo.clearbit.com/stripe.com',
    websiteUrl: 'https://stripe.com',
    docsUrl: 'https://stripe.com/docs',
    baseUrl: 'https://api.stripe.com/v1',
    pricing: { model: 'usage', description: '2.9% + 30¢ per transaction', tiers: [{ name: 'Pay as you go', price: 0, features: ['No monthly fee', 'Transaction fees apply'] }] },
    features: ['Recurring billing', 'Global payments', 'Fraud detection', 'PCI compliant', 'Webhooks', 'SDKs for all languages'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 78,
    uptime30d: 99.99,
    uptime90d: 99.98,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'razorpay',
    name: 'Razorpay',
    description: 'India\'s leading payment gateway. Accept payments via credit/debit cards, UPI, netbanking, and wallets.',
    category: 'payments',
    tags: ['payment', 'india', 'upi', 'gateway'],
    logoUrl: 'https://logo.clearbit.com/razorpay.com',
    websiteUrl: 'https://razorpay.com',
    docsUrl: 'https://razorpay.com/docs',
    baseUrl: 'https://api.razorpay.com/v1',
    pricing: { model: 'usage', description: '2% per transaction', tiers: [] },
    features: ['UPI payments', 'EMI support', 'Smart collect', 'Instant settlements'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 120,
    uptime30d: 99.95,
    uptime90d: 99.92,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'paypal',
    name: 'PayPal',
    description: 'Accept PayPal, credit/debit cards, and local payment methods. 400M+ active accounts worldwide.',
    category: 'payments',
    tags: ['payment', 'wallet', 'checkout', 'international'],
    logoUrl: 'https://logo.clearbit.com/paypal.com',
    websiteUrl: 'https://developer.paypal.com',
    docsUrl: 'https://developer.paypal.com/docs',
    baseUrl: 'https://api-m.paypal.com/v2',
    pricing: { model: 'usage', description: '3.49% + fixed fee per transaction', tiers: [] },
    features: ['PayPal wallet', 'Buy Now Pay Later', 'Fraud protection', 'Global coverage'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 95,
    uptime30d: 99.97,
    uptime90d: 99.95,
    isVerified: true,
    isFeatured: false,
  },
  {
    slug: 'square',
    name: 'Square',
    description: 'Payments, POS, and business tools. Accept in-person and online payments seamlessly.',
    category: 'payments',
    tags: ['payment', 'pos', 'in-person', 'ecommerce'],
    logoUrl: 'https://logo.clearbit.com/squareup.com',
    websiteUrl: 'https://developer.squareup.com',
    docsUrl: 'https://developer.squareup.com/docs',
    baseUrl: 'https://connect.squareup.com/v2',
    pricing: { model: 'usage', description: '2.6% + 10¢ in-person, 2.9% + 30¢ online', tiers: [] },
    features: ['In-person payments', 'Online checkout', 'Invoicing', 'Inventory management'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 88,
    uptime30d: 99.93,
    uptime90d: 99.90,
    isVerified: true,
  },
  {
    slug: 'cashfree',
    name: 'Cashfree Payments',
    description: 'Fast-growing Indian payment gateway with instant payouts, UPI, and payment links.',
    category: 'payments',
    tags: ['payment', 'india', 'payout', 'upi'],
    logoUrl: 'https://logo.clearbit.com/cashfree.com',
    websiteUrl: 'https://cashfree.com',
    docsUrl: 'https://docs.cashfree.com',
    baseUrl: 'https://api.cashfree.com/pg',
    pricing: { model: 'usage', description: '1.75% per transaction', tiers: [] },
    features: ['Instant payouts', 'UPI autopay', 'Payment links', 'Bank transfer'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 135,
    uptime30d: 99.91,
    uptime90d: 99.88,
    isVerified: false,
  },

  // ======== AUTH & IDENTITY ========
  {
    slug: 'auth0',
    name: 'Auth0',
    description: 'The identity platform for application teams. Add authentication and authorization in minutes.',
    category: 'auth',
    tags: ['authentication', 'oauth', 'jwt', 'sso', 'identity'],
    logoUrl: 'https://logo.clearbit.com/auth0.com',
    websiteUrl: 'https://auth0.com',
    docsUrl: 'https://auth0.com/docs',
    baseUrl: 'https://YOUR_DOMAIN.auth0.com',
    pricing: { model: 'freemium', description: 'Free up to 7,500 MAU', tiers: [{ name: 'Free', price: 0, mau: 7500 }, { name: 'Pro', price: 23 }] },
    features: ['Universal Login', 'MFA', 'SSO', 'Anomaly detection', 'Rules & Hooks', 'Social login'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 65,
    uptime30d: 99.99,
    uptime90d: 99.99,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'clerk',
    name: 'Clerk',
    description: 'The most comprehensive User Management Platform. Drop-in auth with beautiful UI components.',
    category: 'auth',
    tags: ['authentication', 'react', 'next.js', 'user-management'],
    logoUrl: 'https://logo.clearbit.com/clerk.com',
    websiteUrl: 'https://clerk.com',
    docsUrl: 'https://clerk.com/docs',
    baseUrl: 'https://api.clerk.com/v1',
    pricing: { model: 'freemium', description: 'Free up to 10,000 MAU', tiers: [{ name: 'Free', price: 0, mau: 10000 }, { name: 'Pro', price: 25 }] },
    features: ['Pre-built components', 'Passwordless auth', 'MFA', 'Organization management', 'Next.js SDK'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 72,
    uptime30d: 99.97,
    uptime90d: 99.96,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'firebase-auth',
    name: 'Firebase Auth',
    description: 'Firebase Authentication provides backend services for authenticating users with passwords, phone numbers, and more.',
    category: 'auth',
    tags: ['authentication', 'firebase', 'google', 'mobile'],
    logoUrl: 'https://logo.clearbit.com/firebase.google.com',
    websiteUrl: 'https://firebase.google.com/products/auth',
    docsUrl: 'https://firebase.google.com/docs/auth',
    baseUrl: 'https://identitytoolkit.googleapis.com/v1',
    pricing: { model: 'free', description: 'Free (up to 10k phone auths/month)', tiers: [] },
    features: ['Email/password', 'Social login', 'Phone auth', 'Anonymous auth', 'Custom auth'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 85,
    uptime30d: 99.98,
    uptime90d: 99.97,
    isVerified: true,
  },

  // ======== EMAIL & MESSAGING ========
  {
    slug: 'sendgrid',
    name: 'SendGrid',
    description: 'Send transactional and marketing emails with industry-leading deliverability.',
    category: 'email',
    tags: ['email', 'transactional', 'marketing', 'smtp'],
    logoUrl: 'https://logo.clearbit.com/sendgrid.com',
    websiteUrl: 'https://sendgrid.com',
    docsUrl: 'https://docs.sendgrid.com',
    baseUrl: 'https://api.sendgrid.com/v3',
    pricing: { model: 'freemium', description: 'Free: 100 emails/day', tiers: [{ name: 'Free', price: 0, emails: '100/day' }, { name: 'Essentials', price: 19.95 }] },
    features: ['Email templates', 'Analytics', 'Bounce management', 'Inbound parse', 'Marketing campaigns'],
    currentStatus: 'DEGRADED',
    avgLatency: 180,
    uptime30d: 99.85,
    uptime90d: 99.89,
    isVerified: true,
    isFeatured: false,
  },
  {
    slug: 'mailgun',
    name: 'Mailgun',
    description: 'Email delivery service for developers. Powerful APIs that enable you to send, receive, and track emails.',
    category: 'email',
    tags: ['email', 'api', 'transactional', 'smtp'],
    logoUrl: 'https://logo.clearbit.com/mailgun.com',
    websiteUrl: 'https://mailgun.com',
    docsUrl: 'https://documentation.mailgun.com',
    baseUrl: 'https://api.mailgun.net/v3',
    pricing: { model: 'freemium', description: 'Free: 100 emails/day for 3 months', tiers: [] },
    features: ['Email validation', 'Templates', 'Routing', 'Analytics', 'Log retention'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 145,
    uptime30d: 99.94,
    uptime90d: 99.91,
    isVerified: true,
  },
  {
    slug: 'resend',
    name: 'Resend',
    description: 'The email API for developers. Send emails using React components or HTML with world-class deliverability.',
    category: 'email',
    tags: ['email', 'react', 'typescript', 'transactional'],
    logoUrl: 'https://logo.clearbit.com/resend.com',
    websiteUrl: 'https://resend.com',
    docsUrl: 'https://resend.com/docs',
    baseUrl: 'https://api.resend.com',
    pricing: { model: 'freemium', description: 'Free: 3,000 emails/month', tiers: [{ name: 'Free', price: 0, emails: '3k/month' }, { name: 'Pro', price: 20 }] },
    features: ['React Email', 'TypeScript SDK', 'Webhooks', 'Analytics', 'Domains'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 98,
    uptime30d: 99.98,
    uptime90d: 99.97,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'postmark',
    name: 'Postmark',
    description: 'Fast, reliable email delivery for transactional emails. 99.9% delivery within 10 seconds.',
    category: 'email',
    tags: ['email', 'transactional', 'deliverability'],
    logoUrl: 'https://logo.clearbit.com/postmarkapp.com',
    websiteUrl: 'https://postmarkapp.com',
    docsUrl: 'https://postmarkapp.com/developer',
    baseUrl: 'https://api.postmarkapp.com',
    pricing: { model: 'usage', description: '$1.25 per 1,000 emails', tiers: [] },
    features: ['Message streams', 'Bounce handling', 'Spam protection', 'Click tracking', '45-day retention'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 92,
    uptime30d: 99.99,
    uptime90d: 99.99,
    isVerified: true,
  },
  {
    slug: 'twilio',
    name: 'Twilio',
    description: 'Cloud communications platform for SMS, voice, video, and email. Power over 10 million developers.',
    category: 'messaging',
    tags: ['sms', 'voice', 'video', 'phone', 'messaging'],
    logoUrl: 'https://logo.clearbit.com/twilio.com',
    websiteUrl: 'https://twilio.com',
    docsUrl: 'https://www.twilio.com/docs',
    baseUrl: 'https://api.twilio.com/2010-04-01',
    pricing: { model: 'usage', description: 'SMS from $0.0079/message', tiers: [] },
    features: ['SMS/MMS', 'Voice calls', 'WhatsApp', 'Verify', 'Lookup', 'Programmable Chat'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 110,
    uptime30d: 99.95,
    uptime90d: 99.93,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'messagebird',
    name: 'MessageBird',
    description: 'Omnichannel communications platform. SMS, WhatsApp, Voice, and more through a single API.',
    category: 'messaging',
    tags: ['sms', 'whatsapp', 'voice', 'omnichannel'],
    logoUrl: 'https://logo.clearbit.com/messagebird.com',
    websiteUrl: 'https://messagebird.com',
    docsUrl: 'https://developers.messagebird.com',
    baseUrl: 'https://rest.messagebird.com',
    pricing: { model: 'usage', description: 'SMS from €0.0045', tiers: [] },
    features: ['SMS', 'WhatsApp Business', 'Voice', 'Flows', 'Inbox'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 130,
    uptime30d: 99.90,
    uptime90d: 99.88,
    isVerified: false,
  },

  // ======== AI & ML ========
  {
    slug: 'openai',
    name: 'OpenAI API',
    description: 'Access GPT-4, GPT-3.5, DALL-E, Whisper, and Embeddings through a simple REST API.',
    category: 'ai',
    tags: ['llm', 'gpt', 'ai', 'text-generation', 'embeddings', 'vision'],
    logoUrl: 'https://logo.clearbit.com/openai.com',
    websiteUrl: 'https://openai.com',
    docsUrl: 'https://platform.openai.com/docs',
    baseUrl: 'https://api.openai.com/v1',
    pricing: { model: 'usage', description: 'GPT-4: $30/$60 per 1M tokens', tiers: [] },
    features: ['GPT-4', 'Chat completions', 'Embeddings', 'DALL-E 3', 'Whisper', 'Fine-tuning'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 850,
    uptime30d: 99.92,
    uptime90d: 99.89,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'anthropic',
    name: 'Anthropic Claude',
    description: 'Claude is an AI assistant from Anthropic focused on safety, accuracy, and helpfulness.',
    category: 'ai',
    tags: ['llm', 'claude', 'ai', 'text-generation', 'safety'],
    logoUrl: 'https://logo.clearbit.com/anthropic.com',
    websiteUrl: 'https://anthropic.com',
    docsUrl: 'https://docs.anthropic.com',
    baseUrl: 'https://api.anthropic.com/v1',
    pricing: { model: 'usage', description: 'Claude 3 Opus: $15/$75 per 1M tokens', tiers: [] },
    features: ['Claude 3 Opus', 'Claude 3 Sonnet', 'Claude 3 Haiku', 'Vision', '200k context window'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 920,
    uptime30d: 99.94,
    uptime90d: 99.91,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'google-gemini',
    name: 'Google Gemini',
    description: 'Google\'s most capable AI model. Multimodal understanding of text, images, audio, and code.',
    category: 'ai',
    tags: ['llm', 'gemini', 'google', 'multimodal', 'ai'],
    logoUrl: 'https://logo.clearbit.com/ai.google.dev',
    websiteUrl: 'https://ai.google.dev',
    docsUrl: 'https://ai.google.dev/docs',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    pricing: { model: 'freemium', description: 'Gemini 1.5 Flash: Free tier available', tiers: [{ name: 'Free', price: 0 }, { name: 'Pay-as-you-go', price: 0.00001875 }] },
    features: ['Gemini 1.5 Pro', 'Gemini 1.5 Flash', 'Multimodal', 'Long context (1M tokens)', 'Code generation'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 680,
    uptime30d: 99.96,
    uptime90d: 99.94,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'groq',
    name: 'Groq',
    description: 'The fastest AI inference platform. Run LLaMA, Mixtral, and Gemma at blazing speeds.',
    category: 'ai',
    tags: ['llm', 'llama', 'inference', 'fast', 'ai'],
    logoUrl: 'https://logo.clearbit.com/groq.com',
    websiteUrl: 'https://groq.com',
    docsUrl: 'https://console.groq.com/docs',
    baseUrl: 'https://api.groq.com/openai/v1',
    pricing: { model: 'freemium', description: 'Free tier: 14,400 requests/day', tiers: [{ name: 'Free', price: 0 }, { name: 'Usage-based', price: 0.000059 }] },
    features: ['LLaMA 3.1', 'Mixtral', 'Gemma', 'OpenAI-compatible', 'Ultra-low latency (<100ms)'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 98,
    uptime30d: 99.91,
    uptime90d: 99.88,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'huggingface',
    name: 'Hugging Face',
    description: 'The AI community platform. Access 300,000+ models for NLP, computer vision, audio, and more.',
    category: 'ai',
    tags: ['ml', 'models', 'transformers', 'nlp', 'ai'],
    logoUrl: 'https://logo.clearbit.com/huggingface.co',
    websiteUrl: 'https://huggingface.co',
    docsUrl: 'https://huggingface.co/docs',
    baseUrl: 'https://api-inference.huggingface.co',
    pricing: { model: 'freemium', description: 'Free inference API available', tiers: [] },
    features: ['Inference API', 'Serverless endpoints', '300k+ models', 'Datasets', 'Spaces'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 1200,
    uptime30d: 99.78,
    uptime90d: 99.75,
    isVerified: true,
  },
  {
    slug: 'replicate',
    name: 'Replicate',
    description: 'Run AI models in the cloud. Deploy open-source models with one API call.',
    category: 'ai',
    tags: ['ml', 'image-generation', 'stable-diffusion', 'ai', 'inference'],
    logoUrl: 'https://logo.clearbit.com/replicate.com',
    websiteUrl: 'https://replicate.com',
    docsUrl: 'https://replicate.com/docs',
    baseUrl: 'https://api.replicate.com/v1',
    pricing: { model: 'usage', description: 'From $0.000225/second compute', tiers: [] },
    features: ['Image generation', 'Video models', 'Language models', 'Custom deployments', 'Webhooks'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 2500,
    uptime30d: 99.82,
    uptime90d: 99.79,
    isVerified: false,
    isFeatured: false,
  },

  // ======== MAPS & LOCATION ========
  {
    slug: 'google-maps',
    name: 'Google Maps Platform',
    description: 'Maps, routes, and places at scale. 250M+ businesses and 1B+ users trust Google Maps.',
    category: 'maps',
    tags: ['maps', 'geocoding', 'directions', 'places', 'location'],
    logoUrl: 'https://logo.clearbit.com/developers.google.com',
    websiteUrl: 'https://developers.google.com/maps',
    docsUrl: 'https://developers.google.com/maps/documentation',
    baseUrl: 'https://maps.googleapis.com/maps/api',
    pricing: { model: 'freemium', description: '$200 free credit/month', tiers: [] },
    features: ['Maps JavaScript', 'Geocoding', 'Directions', 'Places', 'Distance Matrix', 'Street View'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 75,
    uptime30d: 99.99,
    uptime90d: 99.99,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'mapbox',
    name: 'Mapbox',
    description: 'Maps and location for developers. Beautiful, customizable maps and navigation APIs.',
    category: 'maps',
    tags: ['maps', 'navigation', 'geocoding', 'custom-maps'],
    logoUrl: 'https://logo.clearbit.com/mapbox.com',
    websiteUrl: 'https://mapbox.com',
    docsUrl: 'https://docs.mapbox.com',
    baseUrl: 'https://api.mapbox.com',
    pricing: { model: 'freemium', description: '50k map loads/month free', tiers: [] },
    features: ['Custom map styles', 'Navigation SDK', 'Geocoding', 'Isochrone API', 'Search Box'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 82,
    uptime30d: 99.97,
    uptime90d: 99.95,
    isVerified: true,
  },

  // ======== STORAGE ========
  {
    slug: 'cloudinary',
    name: 'Cloudinary',
    description: 'Cloud-based image and video management platform. Transform, optimize, and deliver media.',
    category: 'storage',
    tags: ['images', 'video', 'media', 'cdn', 'transformation'],
    logoUrl: 'https://logo.clearbit.com/cloudinary.com',
    websiteUrl: 'https://cloudinary.com',
    docsUrl: 'https://cloudinary.com/documentation',
    baseUrl: 'https://api.cloudinary.com/v1_1',
    pricing: { model: 'freemium', description: 'Free: 25 credits/month', tiers: [] },
    features: ['Image transformation', 'Video optimization', 'AI tagging', 'CDN delivery', 'Background removal'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 65,
    uptime30d: 99.98,
    uptime90d: 99.96,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'aws-s3',
    name: 'AWS S3',
    description: 'Object storage with industry-leading scalability, availability, security, and performance.',
    category: 'storage',
    tags: ['storage', 'aws', 'object-storage', 's3', 'bucket'],
    logoUrl: 'https://logo.clearbit.com/aws.amazon.com',
    websiteUrl: 'https://aws.amazon.com/s3',
    docsUrl: 'https://docs.aws.amazon.com/s3',
    baseUrl: 'https://s3.amazonaws.com',
    pricing: { model: 'usage', description: '$0.023/GB storage', tiers: [] },
    features: ['Versioning', 'Lifecycle policies', 'Event notifications', 'Replication', 'Static hosting', 'CDN integration'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 45,
    uptime30d: 99.999,
    uptime90d: 99.999,
    isVerified: true,
    isFeatured: false,
  },
  {
    slug: 'cloudflare-r2',
    name: 'Cloudflare R2',
    description: 'S3-compatible object storage without egress fees. Built on Cloudflare\'s global network.',
    category: 'storage',
    tags: ['storage', 's3-compatible', 'cloudflare', 'no-egress'],
    logoUrl: 'https://logo.clearbit.com/cloudflare.com',
    websiteUrl: 'https://cloudflare.com/developer-platform/r2',
    docsUrl: 'https://developers.cloudflare.com/r2',
    baseUrl: 'https://<account-id>.r2.cloudflarestorage.com',
    pricing: { model: 'freemium', description: 'Free: 10GB/month', tiers: [] },
    features: ['Zero egress fees', 'S3-compatible', 'Global CDN', 'Event notifications', 'Workers integration'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 38,
    uptime30d: 99.99,
    uptime90d: 99.99,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'uploadthing',
    name: 'UploadThing',
    description: 'The easiest way to add file uploads to your full-stack TypeScript application.',
    category: 'storage',
    tags: ['upload', 'files', 'typescript', 'next.js'],
    logoUrl: 'https://logo.clearbit.com/uploadthing.com',
    websiteUrl: 'https://uploadthing.com',
    docsUrl: 'https://docs.uploadthing.com',
    baseUrl: 'https://uploadthing.com/api',
    pricing: { model: 'freemium', description: 'Free: 2GB storage', tiers: [] },
    features: ['TypeScript-first', 'Next.js integration', 'File validation', 'Presigned URLs', 'CDN delivery'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 95,
    uptime30d: 99.90,
    uptime90d: 99.87,
    isVerified: false,
  },

  // ======== DATABASES ========
  {
    slug: 'supabase',
    name: 'Supabase',
    description: 'The open-source Firebase alternative. Postgres database, Auth, instant APIs, Edge Functions, Realtime.',
    category: 'database',
    tags: ['postgres', 'realtime', 'auth', 'storage', 'serverless'],
    logoUrl: 'https://logo.clearbit.com/supabase.com',
    websiteUrl: 'https://supabase.com',
    docsUrl: 'https://supabase.com/docs',
    baseUrl: 'https://YOUR_PROJECT.supabase.co/rest/v1',
    pricing: { model: 'freemium', description: 'Free: 500MB DB, 1GB storage', tiers: [] },
    features: ['PostgreSQL', 'Auto-generated REST API', 'Realtime subscriptions', 'Row Level Security', 'Edge Functions'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 55,
    uptime30d: 99.96,
    uptime90d: 99.94,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'neon',
    name: 'Neon',
    description: 'Serverless Postgres with autoscaling, branching, and a generous free tier.',
    category: 'database',
    tags: ['postgres', 'serverless', 'branching', 'sql'],
    logoUrl: 'https://logo.clearbit.com/neon.tech',
    websiteUrl: 'https://neon.tech',
    docsUrl: 'https://neon.tech/docs',
    baseUrl: 'https://console.neon.tech/api/v2',
    pricing: { model: 'freemium', description: 'Free tier available', tiers: [] },
    features: ['Database branching', 'Autoscaling', 'Scale to zero', 'Postgres 16', 'Instant clone'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 48,
    uptime30d: 99.95,
    uptime90d: 99.93,
    isVerified: true,
    isFeatured: false,
  },
  {
    slug: 'planetscale',
    name: 'PlanetScale',
    description: 'The world\'s most advanced serverless MySQL platform with unlimited horizontal scaling.',
    category: 'database',
    tags: ['mysql', 'serverless', 'branching', 'vitess'],
    logoUrl: 'https://logo.clearbit.com/planetscale.com',
    websiteUrl: 'https://planetscale.com',
    docsUrl: 'https://planetscale.com/docs',
    baseUrl: 'https://api.planetscale.com/v1',
    pricing: { model: 'paid', description: 'Starting at $39/month', tiers: [] },
    features: ['Database branching', 'Non-blocking schema changes', 'Query insights', 'Multi-region', 'Horizontal sharding'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 52,
    uptime30d: 99.99,
    uptime90d: 99.98,
    isVerified: true,
  },
  {
    slug: 'turso',
    name: 'Turso',
    description: 'SQLite for production. Edge-deployed database with per-user databases at scale.',
    category: 'database',
    tags: ['sqlite', 'edge', 'distributed', 'libsql'],
    logoUrl: 'https://logo.clearbit.com/turso.tech',
    websiteUrl: 'https://turso.tech',
    docsUrl: 'https://docs.turso.tech',
    baseUrl: 'https://api.turso.tech',
    pricing: { model: 'freemium', description: 'Free: 500 DBs, 1B row reads', tiers: [] },
    features: ['SQLite compatible', 'Edge deployment', 'Multi-tenant', 'Embedded replicas', 'Branching'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 25,
    uptime30d: 99.93,
    uptime90d: 99.90,
    isVerified: false,
  },
  {
    slug: 'firebase-realtime',
    name: 'Firebase Realtime DB',
    description: 'NoSQL cloud database that synchronizes data in realtime across all clients.',
    category: 'database',
    tags: ['nosql', 'realtime', 'firebase', 'google', 'sync'],
    logoUrl: 'https://logo.clearbit.com/firebase.google.com',
    websiteUrl: 'https://firebase.google.com/products/realtime-database',
    docsUrl: 'https://firebase.google.com/docs/database',
    baseUrl: 'https://YOUR_PROJECT.firebaseio.com',
    pricing: { model: 'freemium', description: 'Free: 1GB storage, 10GB/month transfer', tiers: [] },
    features: ['Realtime sync', 'Offline support', 'Security rules', 'REST API', 'SDKs for all platforms'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 65,
    uptime30d: 99.97,
    uptime90d: 99.96,
    isVerified: true,
  },

  // ======== SEARCH ========
  {
    slug: 'algolia',
    name: 'Algolia',
    description: 'AI-powered search & discovery platform. Build fast, relevant search for your users.',
    category: 'search',
    tags: ['search', 'ai', 'autocomplete', 'relevance', 'typo-tolerance'],
    logoUrl: 'https://logo.clearbit.com/algolia.com',
    websiteUrl: 'https://algolia.com',
    docsUrl: 'https://www.algolia.com/doc',
    baseUrl: 'https://YOUR_APP_ID.algolia.net',
    pricing: { model: 'freemium', description: 'Free: 10k search requests/month', tiers: [] },
    features: ['Typo tolerance', 'Faceted search', 'Geo-search', 'Personalization', 'Neural search', 'Instant search'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 35,
    uptime30d: 99.99,
    uptime90d: 99.98,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'meilisearch',
    name: 'Meilisearch',
    description: 'The open-source, lightning-fast, relevant search engine. Plug and play REST API.',
    category: 'search',
    tags: ['search', 'open-source', 'self-hosted', 'fast'],
    logoUrl: 'https://logo.clearbit.com/meilisearch.com',
    websiteUrl: 'https://meilisearch.com',
    docsUrl: 'https://docs.meilisearch.com',
    baseUrl: 'https://YOUR_INSTANCE.meilisearch.io',
    pricing: { model: 'freemium', description: 'Self-hosted free, Cloud from $30/month', tiers: [] },
    features: ['Typo tolerance', 'Faceted search', 'Multi-search', 'Geosearch', 'Custom ranking'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 28,
    uptime30d: 99.95,
    uptime90d: 99.92,
    isVerified: false,
  },
  {
    slug: 'typesense',
    name: 'Typesense',
    description: 'Open source, typo tolerant instant search engine. Faster alternative to Algolia.',
    category: 'search',
    tags: ['search', 'open-source', 'instant', 'self-hosted'],
    logoUrl: 'https://logo.clearbit.com/typesense.org',
    websiteUrl: 'https://typesense.org',
    docsUrl: 'https://typesense.org/docs',
    baseUrl: 'https://YOUR_INSTANCE.a1.typesense.net',
    pricing: { model: 'freemium', description: 'Self-hosted free, Cloud available', tiers: [] },
    features: ['Instant search', 'Typo tolerance', 'Federated search', 'Vector search', 'Geosearch'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 22,
    uptime30d: 99.94,
    uptime90d: 99.91,
    isVerified: false,
  },

  // ======== ANALYTICS ========
  {
    slug: 'mixpanel',
    name: 'Mixpanel',
    description: 'Product analytics that helps teams build better products through data-driven insights.',
    category: 'analytics',
    tags: ['analytics', 'events', 'product', 'funnel', 'retention'],
    logoUrl: 'https://logo.clearbit.com/mixpanel.com',
    websiteUrl: 'https://mixpanel.com',
    docsUrl: 'https://developer.mixpanel.com/reference',
    baseUrl: 'https://api.mixpanel.com',
    pricing: { model: 'freemium', description: 'Free: 20M events/month', tiers: [] },
    features: ['Event tracking', 'Funnels', 'Retention analysis', 'A/B testing', 'Cohort analysis', 'Predictions'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 125,
    uptime30d: 99.93,
    uptime90d: 99.91,
    isVerified: true,
  },
  {
    slug: 'amplitude',
    name: 'Amplitude',
    description: 'Digital analytics platform for understanding user behavior and driving product growth.',
    category: 'analytics',
    tags: ['analytics', 'product', 'behavioral', 'growth'],
    logoUrl: 'https://logo.clearbit.com/amplitude.com',
    websiteUrl: 'https://amplitude.com',
    docsUrl: 'https://www.docs.developers.amplitude.com',
    baseUrl: 'https://api.amplitude.com',
    pricing: { model: 'freemium', description: 'Free: unlimited events (sampled)', tiers: [] },
    features: ['Behavioral analytics', 'Cohorts', 'Experiments', 'Forecasting', 'Collaboration'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 140,
    uptime30d: 99.91,
    uptime90d: 99.88,
    isVerified: true,
  },
  {
    slug: 'posthog',
    name: 'PostHog',
    description: 'The open-source product analytics, session recording, feature flags, and A/B testing platform.',
    category: 'analytics',
    tags: ['analytics', 'open-source', 'session-recording', 'feature-flags'],
    logoUrl: 'https://logo.clearbit.com/posthog.com',
    websiteUrl: 'https://posthog.com',
    docsUrl: 'https://posthog.com/docs',
    baseUrl: 'https://app.posthog.com',
    pricing: { model: 'freemium', description: 'Free: 1M events/month', tiers: [] },
    features: ['Product analytics', 'Session replay', 'Feature flags', 'A/B testing', 'Surveys', 'Self-hostable'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 95,
    uptime30d: 99.94,
    uptime90d: 99.92,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'plausible',
    name: 'Plausible Analytics',
    description: 'Simple and privacy-friendly Google Analytics alternative. No cookies, GDPR compliant.',
    category: 'analytics',
    tags: ['analytics', 'privacy', 'gdpr', 'lightweight'],
    logoUrl: 'https://logo.clearbit.com/plausible.io',
    websiteUrl: 'https://plausible.io',
    docsUrl: 'https://plausible.io/docs',
    baseUrl: 'https://plausible.io/api/v1',
    pricing: { model: 'paid', description: 'From $9/month for 10k pageviews', tiers: [] },
    features: ['Cookie-free', 'GDPR compliant', 'Real-time dashboard', 'Goal tracking', 'API access'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 72,
    uptime30d: 99.97,
    uptime90d: 99.95,
    isVerified: false,
  },

  // ======== AI & ML (extended) ========
  {
    slug: 'cohere',
    name: 'Cohere',
    description: 'Enterprise AI platform for text generation, embeddings, classification, and semantic search.',
    category: 'ai',
    tags: ['llm', 'embeddings', 'classification', 'enterprise', 'ai'],
    logoUrl: 'https://logo.clearbit.com/cohere.com',
    websiteUrl: 'https://cohere.com',
    docsUrl: 'https://docs.cohere.com',
    baseUrl: 'https://api.cohere.ai/v1',
    pricing: { model: 'freemium', description: 'Free trial: 100 API calls/month', tiers: [] },
    features: ['Command R+', 'Embeddings', 'Rerank', 'Classify', 'RAG support', 'Multilingual'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 620,
    uptime30d: 99.91,
    uptime90d: 99.88,
    isVerified: true,
    isFeatured: false,
  },
  {
    slug: 'mistral',
    name: 'Mistral AI',
    description: 'Frontier AI models built for efficiency and performance. Open-weight and enterprise models.',
    category: 'ai',
    tags: ['llm', 'open-source', 'efficiency', 'ai'],
    logoUrl: 'https://logo.clearbit.com/mistral.ai',
    websiteUrl: 'https://mistral.ai',
    docsUrl: 'https://docs.mistral.ai',
    baseUrl: 'https://api.mistral.ai/v1',
    pricing: { model: 'usage', description: 'Mistral 7B: $0.25 per 1M tokens', tiers: [] },
    features: ['Mistral Large', 'Mistral Small', 'Codestral', 'OpenAI-compatible', 'Function calling', 'JSON mode'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 540,
    uptime30d: 99.89,
    uptime90d: 99.86,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'AI audio platform. Generate natural-sounding speech in 29 languages with voice cloning.',
    category: 'ai',
    tags: ['tts', 'voice', 'speech', 'audio', 'ai'],
    logoUrl: 'https://logo.clearbit.com/elevenlabs.io',
    websiteUrl: 'https://elevenlabs.io',
    docsUrl: 'https://docs.elevenlabs.io',
    baseUrl: 'https://api.elevenlabs.io/v1',
    pricing: { model: 'freemium', description: 'Free: 10k characters/month', tiers: [] },
    features: ['Text-to-speech', 'Voice cloning', '29 languages', 'Voice design', 'Dubbing', 'Sound effects'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 780,
    uptime30d: 99.87,
    uptime90d: 99.84,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'deepgram',
    name: 'Deepgram',
    description: 'Speech AI platform for real-time and batch transcription, text-to-speech, and audio intelligence.',
    category: 'ai',
    tags: ['speech-to-text', 'transcription', 'audio', 'voice', 'ai'],
    logoUrl: 'https://logo.clearbit.com/deepgram.com',
    websiteUrl: 'https://deepgram.com',
    docsUrl: 'https://developers.deepgram.com',
    baseUrl: 'https://api.deepgram.com/v1',
    pricing: { model: 'freemium', description: 'Free: $200 credit on signup', tiers: [] },
    features: ['Real-time transcription', 'Batch transcription', 'Text-to-speech', 'Language detection', 'Speaker diarization'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 320,
    uptime30d: 99.92,
    uptime90d: 99.90,
    isVerified: true,
  },
  {
    slug: 'stability-ai',
    name: 'Stability AI',
    description: 'Stable Diffusion and generative AI models for image, video, and 3D creation.',
    category: 'ai',
    tags: ['image-generation', 'stable-diffusion', 'generative-ai', 'art'],
    logoUrl: 'https://logo.clearbit.com/stability.ai',
    websiteUrl: 'https://stability.ai',
    docsUrl: 'https://platform.stability.ai/docs',
    baseUrl: 'https://api.stability.ai/v2beta',
    pricing: { model: 'usage', description: 'From $0.065 per image', tiers: [] },
    features: ['Stable Diffusion 3', 'Image-to-image', 'Inpainting', 'Upscaling', 'Video generation', 'Sketch-to-image'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 3200,
    uptime30d: 99.80,
    uptime90d: 99.77,
    isVerified: true,
    isFeatured: false,
  },
  {
    slug: 'together-ai',
    name: 'Together AI',
    description: 'Run and fine-tune open-source AI models in the cloud with fast, affordable inference.',
    category: 'ai',
    tags: ['llm', 'open-source', 'inference', 'fine-tuning', 'ai'],
    logoUrl: 'https://logo.clearbit.com/together.ai',
    websiteUrl: 'https://together.ai',
    docsUrl: 'https://docs.together.ai',
    baseUrl: 'https://api.together.xyz/v1',
    pricing: { model: 'usage', description: 'From $0.0002 per 1M tokens', tiers: [] },
    features: ['70+ open-source models', 'OpenAI-compatible', 'Fine-tuning', 'Serverless inference', 'Dedicated GPUs'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 180,
    uptime30d: 99.85,
    uptime90d: 99.82,
    isVerified: false,
  },
  {
    slug: 'perplexity',
    name: 'Perplexity AI',
    description: 'AI-powered answer engine with real-time web search. Build search-augmented AI applications.',
    category: 'ai',
    tags: ['search', 'llm', 'web-search', 'rag', 'ai'],
    logoUrl: 'https://logo.clearbit.com/perplexity.ai',
    websiteUrl: 'https://perplexity.ai',
    docsUrl: 'https://docs.perplexity.ai',
    baseUrl: 'https://api.perplexity.ai',
    pricing: { model: 'usage', description: 'From $0.2 per 1M tokens', tiers: [] },
    features: ['Online models with web search', 'Citations', 'Sonar models', 'OpenAI-compatible', 'Streaming'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 1100,
    uptime30d: 99.88,
    uptime90d: 99.85,
    isVerified: false,
  },
  {
    slug: 'assemblyai',
    name: 'AssemblyAI',
    description: 'Speech AI APIs for transcription, summarization, sentiment analysis, and audio intelligence.',
    category: 'ai',
    tags: ['transcription', 'speech-to-text', 'audio', 'nlp', 'ai'],
    logoUrl: 'https://logo.clearbit.com/assemblyai.com',
    websiteUrl: 'https://assemblyai.com',
    docsUrl: 'https://www.assemblyai.com/docs',
    baseUrl: 'https://api.assemblyai.com/v2',
    pricing: { model: 'usage', description: '$0.65/hour of audio', tiers: [] },
    features: ['Transcription', 'Speaker diarization', 'Sentiment analysis', 'Chapter detection', 'LeMUR AI'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 2800,
    uptime30d: 99.90,
    uptime90d: 99.87,
    isVerified: true,
  },

  // ======== DEV TOOLS (extended) ========
  {
    slug: 'sentry',
    name: 'Sentry',
    description: 'Application monitoring platform. Track errors, performance issues, and user sessions in real time.',
    category: 'devtools',
    tags: ['error-tracking', 'monitoring', 'performance', 'apm', 'logging'],
    logoUrl: 'https://logo.clearbit.com/sentry.io',
    websiteUrl: 'https://sentry.io',
    docsUrl: 'https://docs.sentry.io',
    baseUrl: 'https://sentry.io/api/0',
    pricing: { model: 'freemium', description: 'Free: 5k errors/month', tiers: [] },
    features: ['Error tracking', 'Performance monitoring', 'Session replay', 'Crons', 'Profiling', 'AI suggestions'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 145,
    uptime30d: 99.96,
    uptime90d: 99.94,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'upstash',
    name: 'Upstash',
    description: 'Serverless Redis and Kafka. Per-request pricing with zero infrastructure management.',
    category: 'database',
    tags: ['redis', 'kafka', 'serverless', 'cache', 'edge'],
    logoUrl: 'https://logo.clearbit.com/upstash.com',
    websiteUrl: 'https://upstash.com',
    docsUrl: 'https://upstash.com/docs',
    baseUrl: 'https://YOUR_ENDPOINT.upstash.io',
    pricing: { model: 'freemium', description: 'Free: 10k commands/day', tiers: [] },
    features: ['Serverless Redis', 'Serverless Kafka', 'Global replication', 'REST API', 'Edge-compatible'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 18,
    uptime30d: 99.99,
    uptime90d: 99.98,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'railway',
    name: 'Railway',
    description: 'Deploy anything instantly. GitHub-connected deployments with automatic scaling and managed databases.',
    category: 'devtools',
    tags: ['deployment', 'cloud', 'docker', 'postgres', 'redis'],
    logoUrl: 'https://logo.clearbit.com/railway.app',
    websiteUrl: 'https://railway.app',
    docsUrl: 'https://docs.railway.app',
    baseUrl: 'https://backboard.railway.app/graphql/v2',
    pricing: { model: 'freemium', description: 'Free: $5 credit/month', tiers: [] },
    features: ['GitHub deployments', 'Database hosting', 'Private networking', 'Cron jobs', 'Volume storage', 'Metrics'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 88,
    uptime30d: 99.93,
    uptime90d: 99.90,
    isVerified: true,
  },
  {
    slug: 'render',
    name: 'Render',
    description: 'Cloud platform for deploying web apps, APIs, databases, and cron jobs with zero DevOps.',
    category: 'devtools',
    tags: ['deployment', 'cloud', 'paas', 'postgres', 'static-sites'],
    logoUrl: 'https://logo.clearbit.com/render.com',
    websiteUrl: 'https://render.com',
    docsUrl: 'https://render.com/docs',
    baseUrl: 'https://api.render.com/v1',
    pricing: { model: 'freemium', description: 'Free static sites, $7/month web services', tiers: [] },
    features: ['Web services', 'Static sites', 'PostgreSQL', 'Redis', 'Cron jobs', 'Auto-deploys'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 95,
    uptime30d: 99.95,
    uptime90d: 99.92,
    isVerified: true,
  },
  {
    slug: 'linear-api',
    name: 'Linear',
    description: 'Issue tracking for high-performance teams. GraphQL API for projects, issues, and workflows.',
    category: 'devtools',
    tags: ['project-management', 'issues', 'graphql', 'productivity'],
    logoUrl: 'https://logo.clearbit.com/linear.app',
    websiteUrl: 'https://linear.app',
    docsUrl: 'https://developers.linear.app',
    baseUrl: 'https://api.linear.app/graphql',
    pricing: { model: 'freemium', description: 'Free: up to 250 issues', tiers: [] },
    features: ['GraphQL API', 'Webhooks', 'OAuth 2.0', 'Issues & cycles', 'Projects & roadmaps', 'Automations'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 68,
    uptime30d: 99.98,
    uptime90d: 99.96,
    isVerified: true,
  },
  {
    slug: 'notion-api',
    name: 'Notion API',
    description: 'Build integrations with Notion. Read and write pages, databases, and blocks programmatically.',
    category: 'devtools',
    tags: ['notes', 'database', 'collaboration', 'cms', 'productivity'],
    logoUrl: 'https://logo.clearbit.com/notion.so',
    websiteUrl: 'https://developers.notion.com',
    docsUrl: 'https://developers.notion.com/docs',
    baseUrl: 'https://api.notion.com/v1',
    pricing: { model: 'free', description: 'Free with Notion account', tiers: [] },
    features: ['Pages & databases', 'Blocks API', 'Search', 'Users', 'Webhooks', 'OAuth'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 230,
    uptime30d: 99.91,
    uptime90d: 99.88,
    isVerified: true,
  },
  {
    slug: 'doppler',
    name: 'Doppler',
    description: 'Universal secrets manager. Store, sync, and rotate secrets across all your environments.',
    category: 'devtools',
    tags: ['secrets', 'environment-variables', 'security', 'config'],
    logoUrl: 'https://logo.clearbit.com/doppler.com',
    websiteUrl: 'https://doppler.com',
    docsUrl: 'https://docs.doppler.com',
    baseUrl: 'https://api.doppler.com/v3',
    pricing: { model: 'freemium', description: 'Free for personal use', tiers: [] },
    features: ['Secret syncing', 'Environment management', 'Access controls', 'Audit logs', 'CLI', 'Secret rotation'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 75,
    uptime30d: 99.97,
    uptime90d: 99.95,
    isVerified: false,
  },

  // ======== SOCIAL & COMMUNICATION ========
  {
    slug: 'discord-api',
    name: 'Discord API',
    description: 'Build bots, apps, and integrations for Discord. Slash commands, webhooks, and rich embeds.',
    category: 'social',
    tags: ['discord', 'bots', 'gaming', 'community', 'webhooks'],
    logoUrl: 'https://logo.clearbit.com/discord.com',
    websiteUrl: 'https://discord.com/developers',
    docsUrl: 'https://discord.com/developers/docs',
    baseUrl: 'https://discord.com/api/v10',
    pricing: { model: 'free', description: 'Free (rate limits apply)', tiers: [] },
    features: ['Slash commands', 'Interactions', 'Webhooks', 'Gateway events', 'Rich embeds', 'Thread management'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 92,
    uptime30d: 99.94,
    uptime90d: 99.91,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'slack-api',
    name: 'Slack API',
    description: 'Bring your tools into Slack. Build apps, bots, and workflows using Slack messaging APIs.',
    category: 'social',
    tags: ['slack', 'messaging', 'bots', 'workspace', 'notifications'],
    logoUrl: 'https://logo.clearbit.com/slack.com',
    websiteUrl: 'https://api.slack.com',
    docsUrl: 'https://api.slack.com/docs',
    baseUrl: 'https://slack.com/api',
    pricing: { model: 'free', description: 'Free with Slack workspace', tiers: [] },
    features: ['Bot framework', 'Block Kit', 'Events API', 'Webhooks', 'Slash commands', 'Workflow builder'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 135,
    uptime30d: 99.96,
    uptime90d: 99.94,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'telegram-bot',
    name: 'Telegram Bot API',
    description: 'Build bots for Telegram. Send messages, media, polls, and create inline keyboards.',
    category: 'social',
    tags: ['telegram', 'bots', 'messaging', 'notifications'],
    logoUrl: 'https://logo.clearbit.com/telegram.org',
    websiteUrl: 'https://core.telegram.org/bots',
    docsUrl: 'https://core.telegram.org/bots/api',
    baseUrl: 'https://api.telegram.org/bot',
    pricing: { model: 'free', description: 'Completely free', tiers: [] },
    features: ['Send messages', 'Inline keyboards', 'Webhooks', 'Polling', 'Media support', 'Payments integration'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 110,
    uptime30d: 99.95,
    uptime90d: 99.93,
    isVerified: true,
  },
  {
    slug: 'twitter-api',
    name: 'X (Twitter) API',
    description: 'Access tweets, users, and trends. Build applications on the X (Twitter) platform.',
    category: 'social',
    tags: ['twitter', 'x', 'social-media', 'tweets', 'trends'],
    logoUrl: 'https://logo.clearbit.com/x.com',
    websiteUrl: 'https://developer.x.com',
    docsUrl: 'https://developer.x.com/en/docs',
    baseUrl: 'https://api.twitter.com/2',
    pricing: { model: 'freemium', description: 'Free: 1,500 tweets/month write access', tiers: [] },
    features: ['Tweet lookup', 'User management', 'Search tweets', 'Streaming', 'Media upload', 'OAuth 2.0'],
    currentStatus: 'DEGRADED',
    avgLatency: 280,
    uptime30d: 98.92,
    uptime90d: 98.85,
    isVerified: true,
  },
  {
    slug: 'instagram-api',
    name: 'Instagram Graph API',
    description: 'Manage Instagram Business accounts, media, insights, and mentions via the Graph API.',
    category: 'social',
    tags: ['instagram', 'social-media', 'media', 'business'],
    logoUrl: 'https://logo.clearbit.com/instagram.com',
    websiteUrl: 'https://developers.facebook.com/products/instagram',
    docsUrl: 'https://developers.facebook.com/docs/instagram-api',
    baseUrl: 'https://graph.instagram.com',
    pricing: { model: 'free', description: 'Free (requires app review for full access)', tiers: [] },
    features: ['Media management', 'Comments', 'Insights', 'Mentions', 'Stories', 'Shopping tags'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 210,
    uptime30d: 99.82,
    uptime90d: 99.78,
    isVerified: true,
  },
  {
    slug: 'youtube-api',
    name: 'YouTube Data API',
    description: 'Access YouTube videos, playlists, channels, and live streams. Manage uploads and captions.',
    category: 'social',
    tags: ['youtube', 'video', 'google', 'streaming', 'channels'],
    logoUrl: 'https://logo.clearbit.com/youtube.com',
    websiteUrl: 'https://developers.google.com/youtube',
    docsUrl: 'https://developers.google.com/youtube/v3',
    baseUrl: 'https://www.googleapis.com/youtube/v3',
    pricing: { model: 'freemium', description: 'Free: 10,000 units/day', tiers: [] },
    features: ['Video search', 'Channel management', 'Upload videos', 'Live streaming', 'Captions', 'Analytics'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 165,
    uptime30d: 99.97,
    uptime90d: 99.96,
    isVerified: true,
  },
  {
    slug: 'linkedin-api',
    name: 'LinkedIn API',
    description: 'Build LinkedIn integrations for profiles, company pages, job postings, and marketing.',
    category: 'social',
    tags: ['linkedin', 'professional', 'social-media', 'jobs', 'marketing'],
    logoUrl: 'https://logo.clearbit.com/linkedin.com',
    websiteUrl: 'https://developer.linkedin.com',
    docsUrl: 'https://learn.microsoft.com/en-us/linkedin',
    baseUrl: 'https://api.linkedin.com/v2',
    pricing: { model: 'freemium', description: 'Free basic access', tiers: [] },
    features: ['Profile data', 'Company pages', 'Share posts', 'Job postings', 'OAuth 2.0', 'Insights'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 195,
    uptime30d: 99.89,
    uptime90d: 99.87,
    isVerified: true,
  },

  // ======== FINANCE ========
  {
    slug: 'plaid',
    name: 'Plaid',
    description: 'Financial infrastructure for fintech. Connect bank accounts, verify income, and move money.',
    category: 'finance',
    tags: ['banking', 'fintech', 'open-banking', 'identity', 'transactions'],
    logoUrl: 'https://logo.clearbit.com/plaid.com',
    websiteUrl: 'https://plaid.com',
    docsUrl: 'https://plaid.com/docs',
    baseUrl: 'https://production.plaid.com',
    pricing: { model: 'usage', description: 'Contact for pricing', tiers: [] },
    features: ['Bank connections', 'Transaction data', 'Identity verification', 'Income verification', 'Payment initiation'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 340,
    uptime30d: 99.97,
    uptime90d: 99.95,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'coingecko',
    name: 'CoinGecko API',
    description: 'Comprehensive cryptocurrency data. Prices, market cap, and exchange data for 10,000+ coins.',
    category: 'finance',
    tags: ['crypto', 'blockchain', 'prices', 'market-data'],
    logoUrl: 'https://logo.clearbit.com/coingecko.com',
    websiteUrl: 'https://coingecko.com',
    docsUrl: 'https://docs.coingecko.com',
    baseUrl: 'https://api.coingecko.com/api/v3',
    pricing: { model: 'freemium', description: 'Free: 30 calls/min', tiers: [] },
    features: ['Price data', 'Market cap', 'Historical data', 'Exchange info', 'DeFi protocols', 'NFTs'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 145,
    uptime30d: 99.90,
    uptime90d: 99.87,
    isVerified: true,
  },
  {
    slug: 'binance-api',
    name: 'Binance API',
    description: "World's largest crypto exchange API. Real-time market data, trading, and account management.",
    category: 'finance',
    tags: ['crypto', 'trading', 'exchange', 'bitcoin', 'market-data'],
    logoUrl: 'https://logo.clearbit.com/binance.com',
    websiteUrl: 'https://binance.com',
    docsUrl: 'https://binance-docs.github.io/apidocs',
    baseUrl: 'https://api.binance.com/api/v3',
    pricing: { model: 'free', description: 'Free with rate limits', tiers: [] },
    features: ['Market data', 'Trading API', 'WebSocket streams', 'Account management', 'Spot & futures', 'Order books'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 48,
    uptime30d: 99.92,
    uptime90d: 99.89,
    isVerified: true,
  },

  // ======== CMS ========
  {
    slug: 'contentful',
    name: 'Contentful',
    description: 'Headless CMS with a powerful content delivery API. Structure, manage, and deliver content anywhere.',
    category: 'cms',
    tags: ['cms', 'headless', 'content', 'api-first', 'graphql'],
    logoUrl: 'https://logo.clearbit.com/contentful.com',
    websiteUrl: 'https://contentful.com',
    docsUrl: 'https://www.contentful.com/developers/docs',
    baseUrl: 'https://cdn.contentful.com/spaces',
    pricing: { model: 'freemium', description: 'Free: 25k API calls/month', tiers: [] },
    features: ['REST & GraphQL APIs', 'Content modeling', 'Localization', 'Webhooks', 'Rich text', 'Assets'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 88,
    uptime30d: 99.98,
    uptime90d: 99.97,
    isVerified: true,
  },
  {
    slug: 'sanity',
    name: 'Sanity',
    description: 'The composable content cloud. Real-time APIs, GROQ query language, and live collaboration.',
    category: 'cms',
    tags: ['cms', 'headless', 'real-time', 'structured-content', 'groq'],
    logoUrl: 'https://logo.clearbit.com/sanity.io',
    websiteUrl: 'https://sanity.io',
    docsUrl: 'https://www.sanity.io/docs',
    baseUrl: 'https://YOUR_PROJECT.api.sanity.io/v2021-06-07',
    pricing: { model: 'freemium', description: 'Free: 500k API requests/month', tiers: [] },
    features: ['GROQ query language', 'Real-time collaboration', 'Portable Text', 'Asset management', 'Custom schemas'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 72,
    uptime30d: 99.96,
    uptime90d: 99.94,
    isVerified: true,
  },
  {
    slug: 'strapi',
    name: 'Strapi',
    description: 'The leading open-source headless CMS. 100% JavaScript, fully customizable, developer-first.',
    category: 'cms',
    tags: ['cms', 'headless', 'open-source', 'rest', 'graphql'],
    logoUrl: 'https://logo.clearbit.com/strapi.io',
    websiteUrl: 'https://strapi.io',
    docsUrl: 'https://docs.strapi.io',
    baseUrl: 'https://YOUR_INSTANCE.strapiapp.com/api',
    pricing: { model: 'freemium', description: 'Self-hosted free, Cloud from $29/month', tiers: [] },
    features: ['Auto-generated REST & GraphQL', 'Content type builder', 'Role management', 'Webhooks', 'Media library'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 95,
    uptime30d: 99.90,
    uptime90d: 99.87,
    isVerified: false,
  },

  // ======== MEDIA & VIDEO ========
  {
    slug: 'mux',
    name: 'Mux',
    description: 'Video API for developers. Embed, stream, and analyze video at scale with minimal infrastructure.',
    category: 'media',
    tags: ['video', 'streaming', 'encoding', 'analytics', 'live'],
    logoUrl: 'https://logo.clearbit.com/mux.com',
    websiteUrl: 'https://mux.com',
    docsUrl: 'https://docs.mux.com',
    baseUrl: 'https://api.mux.com',
    pricing: { model: 'usage', description: 'Storage from $0.008/min', tiers: [] },
    features: ['On-demand video', 'Live streaming', 'Real-time video', 'Analytics', 'Player SDK', 'Thumbnail API'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 125,
    uptime30d: 99.96,
    uptime90d: 99.94,
    isVerified: true,
  },
  {
    slug: 'agora',
    name: 'Agora',
    description: 'Real-time voice and video APIs. Build live audio/video calling into any app in minutes.',
    category: 'media',
    tags: ['video', 'voice', 'real-time', 'webrtc', 'live'],
    logoUrl: 'https://logo.clearbit.com/agora.io',
    websiteUrl: 'https://agora.io',
    docsUrl: 'https://docs.agora.io',
    baseUrl: 'https://api.agora.io/v1',
    pricing: { model: 'freemium', description: 'Free: 10k minutes/month', tiers: [] },
    features: ['Video calling', 'Voice calling', 'Live streaming', 'Interactive whiteboard', 'Recording', 'Chat'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 85,
    uptime30d: 99.93,
    uptime90d: 99.90,
    isVerified: true,
  },
  {
    slug: 'stream-chat',
    name: 'Stream',
    description: 'Chat messaging, activity feeds, and video calling APIs. Scalable to billions of users.',
    category: 'media',
    tags: ['chat', 'messaging', 'activity-feed', 'video', 'scalable'],
    logoUrl: 'https://logo.clearbit.com/getstream.io',
    websiteUrl: 'https://getstream.io',
    docsUrl: 'https://getstream.io/chat/docs',
    baseUrl: 'https://chat.stream-io-api.com',
    pricing: { model: 'freemium', description: 'Free: 100 MAU forever', tiers: [] },
    features: ['Chat SDK', 'Activity Feeds', 'Video & Audio', 'Push notifications', 'Moderation', 'Offline support'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 78,
    uptime30d: 99.97,
    uptime90d: 99.95,
    isVerified: true,
  },

  // ======== OBSERVABILITY ========
  {
    slug: 'datadog',
    name: 'Datadog',
    description: 'Monitoring and analytics for cloud applications. Metrics, traces, logs, and dashboards.',
    category: 'observability',
    tags: ['monitoring', 'apm', 'logs', 'metrics', 'dashboards'],
    logoUrl: 'https://logo.clearbit.com/datadoghq.com',
    websiteUrl: 'https://datadoghq.com',
    docsUrl: 'https://docs.datadoghq.com',
    baseUrl: 'https://api.datadoghq.com/api/v2',
    pricing: { model: 'usage', description: '$15/host/month for infrastructure', tiers: [] },
    features: ['Infrastructure monitoring', 'APM', 'Log management', 'RUM', 'Synthetic tests', 'Security monitoring'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 115,
    uptime30d: 99.98,
    uptime90d: 99.97,
    isVerified: true,
  },
  {
    slug: 'newrelic',
    name: 'New Relic',
    description: 'Full-stack observability platform. APM, infrastructure, logs, and real user monitoring.',
    category: 'observability',
    tags: ['monitoring', 'apm', 'observability', 'logs', 'infrastructure'],
    logoUrl: 'https://logo.clearbit.com/newrelic.com',
    websiteUrl: 'https://newrelic.com',
    docsUrl: 'https://docs.newrelic.com',
    baseUrl: 'https://api.newrelic.com/graphql',
    pricing: { model: 'freemium', description: 'Free: 100GB data/month', tiers: [] },
    features: ['APM', 'Infrastructure monitoring', 'Log management', 'Distributed tracing', 'Alerts', 'Dashboards'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 130,
    uptime30d: 99.97,
    uptime90d: 99.95,
    isVerified: true,
  },
  {
    slug: 'betterstack',
    name: 'Better Stack',
    description: 'Uptime monitoring, incident management, status pages, and log management in one platform.',
    category: 'observability',
    tags: ['uptime', 'monitoring', 'incidents', 'status-page', 'logs'],
    logoUrl: 'https://logo.clearbit.com/betterstack.com',
    websiteUrl: 'https://betterstack.com',
    docsUrl: 'https://betterstack.com/docs',
    baseUrl: 'https://uptime.betterstack.com/api/v2',
    pricing: { model: 'freemium', description: 'Free: 10 monitors', tiers: [] },
    features: ['Uptime monitoring', 'Status pages', 'Incident management', 'On-call scheduling', 'Log management'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 68,
    uptime30d: 99.99,
    uptime90d: 99.98,
    isVerified: true,
  },

  // ======== PAYMENTS (extended) ========
  {
    slug: 'adyen',
    name: 'Adyen',
    description: 'Global payments platform for enterprises. Accept payments anywhere, in any channel.',
    category: 'payments',
    tags: ['payment', 'enterprise', 'global', 'omnichannel', 'issuing'],
    logoUrl: 'https://logo.clearbit.com/adyen.com',
    websiteUrl: 'https://adyen.com',
    docsUrl: 'https://docs.adyen.com',
    baseUrl: 'https://checkout-test.adyen.com/checkout/v71',
    pricing: { model: 'usage', description: 'Interchange + 0.3% + €0.13', tiers: [] },
    features: ['Global payments', 'In-store POS', 'Risk management', 'Fraud detection', 'Issuing', 'Terminal API'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 82,
    uptime30d: 99.99,
    uptime90d: 99.98,
    isVerified: true,
  },
  {
    slug: 'braintree',
    name: 'Braintree',
    description: "PayPal's developer-friendly payment gateway. Accept cards, PayPal, Venmo, and more.",
    category: 'payments',
    tags: ['payment', 'paypal', 'cards', 'venmo', 'gateway'],
    logoUrl: 'https://logo.clearbit.com/braintreepayments.com',
    websiteUrl: 'https://developer.paypal.com/braintree',
    docsUrl: 'https://developer.paypal.com/braintree/docs',
    baseUrl: 'https://api.braintreegateway.com',
    pricing: { model: 'usage', description: '2.59% + $0.49 per transaction', tiers: [] },
    features: ['Credit/debit cards', 'PayPal', 'Venmo', 'ACH', 'Vault', 'Recurring billing'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 105,
    uptime30d: 99.95,
    uptime90d: 99.93,
    isVerified: true,
  },
  {
    slug: 'lemonsqueezy',
    name: 'Lemon Squeezy',
    description: 'Payments, tax, and subscriptions for software companies. Built for SaaS and indie hackers.',
    category: 'payments',
    tags: ['payment', 'subscriptions', 'saas', 'tax', 'billing'],
    logoUrl: 'https://logo.clearbit.com/lemonsqueezy.com',
    websiteUrl: 'https://lemonsqueezy.com',
    docsUrl: 'https://docs.lemonsqueezy.com',
    baseUrl: 'https://api.lemonsqueezy.com/v1',
    pricing: { model: 'usage', description: '5% + payment processing fees', tiers: [] },
    features: ['Subscriptions', 'One-time payments', 'Tax handling', 'License keys', 'Webhooks', 'Checkout'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 115,
    uptime30d: 99.93,
    uptime90d: 99.90,
    isVerified: false,
  },

  // ======== WEATHER & GEO ========
  {
    slug: 'openweathermap',
    name: 'OpenWeatherMap',
    description: 'Weather data for any location on earth. Current conditions, forecasts, and historical data.',
    category: 'weather',
    tags: ['weather', 'forecast', 'climate', 'temperature', 'geolocation'],
    logoUrl: 'https://logo.clearbit.com/openweathermap.org',
    websiteUrl: 'https://openweathermap.org/api',
    docsUrl: 'https://openweathermap.org/api',
    baseUrl: 'https://api.openweathermap.org/data/3.0',
    pricing: { model: 'freemium', description: 'Free: 1,000 calls/day', tiers: [] },
    features: ['Current weather', '5-day forecast', '16-day forecast', 'Historical data', 'Air quality', 'Weather maps'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 125,
    uptime30d: 99.92,
    uptime90d: 99.89,
    isVerified: true,
  },
  {
    slug: 'ipinfo',
    name: 'IPinfo',
    description: 'IP address data API. Get geolocation, ASN, carrier, and company data for any IP address.',
    category: 'weather',
    tags: ['ip', 'geolocation', 'asn', 'security', 'network'],
    logoUrl: 'https://logo.clearbit.com/ipinfo.io',
    websiteUrl: 'https://ipinfo.io',
    docsUrl: 'https://ipinfo.io/developers',
    baseUrl: 'https://ipinfo.io',
    pricing: { model: 'freemium', description: 'Free: 50k requests/month', tiers: [] },
    features: ['IP geolocation', 'ASN data', 'Carrier info', 'Company lookup', 'Abuse detection', 'Privacy detection'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 22,
    uptime30d: 99.99,
    uptime90d: 99.98,
    isVerified: true,
  },
  {
    slug: 'maxmind',
    name: 'MaxMind GeoIP2',
    description: 'Industry-leading IP intelligence. Accurate geolocation and fraud detection for any IP address.',
    category: 'weather',
    tags: ['ip', 'geolocation', 'fraud', 'security', 'database'],
    logoUrl: 'https://logo.clearbit.com/maxmind.com',
    websiteUrl: 'https://maxmind.com',
    docsUrl: 'https://dev.maxmind.com/geoip/docs',
    baseUrl: 'https://geoip.maxmind.com/geoip/v2.1',
    pricing: { model: 'usage', description: '$6 per 1,000 queries', tiers: [] },
    features: ['IP geolocation', 'ISP detection', 'Proxy detection', 'Anonymous IP', 'minFraud', 'Downloadable DB'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 18,
    uptime30d: 99.99,
    uptime90d: 99.99,
    isVerified: true,
  },

  // ======== AUTH (extended) ========
  {
    slug: 'okta',
    name: 'Okta',
    description: 'Enterprise identity platform. SSO, MFA, lifecycle management, and API access management.',
    category: 'auth',
    tags: ['sso', 'identity', 'enterprise', 'mfa', 'saml', 'oauth'],
    logoUrl: 'https://logo.clearbit.com/okta.com',
    websiteUrl: 'https://okta.com',
    docsUrl: 'https://developer.okta.com/docs',
    baseUrl: 'https://YOUR_DOMAIN.okta.com/api/v1',
    pricing: { model: 'freemium', description: 'Free: 100 MAU', tiers: [] },
    features: ['Single Sign-On', 'MFA', 'Lifecycle Management', 'API Access Management', 'SAML', 'SCIM'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 88,
    uptime30d: 99.99,
    uptime90d: 99.98,
    isVerified: true,
  },
  {
    slug: 'stytch',
    name: 'Stytch',
    description: 'Modern authentication with passwordless-first flows. Built for B2C and B2B products.',
    category: 'auth',
    tags: ['authentication', 'passwordless', 'b2b', 'sso', 'magic-link'],
    logoUrl: 'https://logo.clearbit.com/stytch.com',
    websiteUrl: 'https://stytch.com',
    docsUrl: 'https://stytch.com/docs',
    baseUrl: 'https://api.stytch.com/v1',
    pricing: { model: 'freemium', description: 'Free: 25 MAU', tiers: [] },
    features: ['Passwordless auth', 'Magic links', 'Passkeys', 'B2B SSO', 'RBAC', 'MFA'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 78,
    uptime30d: 99.97,
    uptime90d: 99.95,
    isVerified: false,
  },

  // ======== TRANSLATION ========
  {
    slug: 'deepl',
    name: 'DeepL API',
    description: "World's most accurate AI translator. Translate text and documents into 30+ languages.",
    category: 'translation',
    tags: ['translation', 'nlp', 'multilingual', 'documents', 'ai'],
    logoUrl: 'https://logo.clearbit.com/deepl.com',
    websiteUrl: 'https://deepl.com',
    docsUrl: 'https://developers.deepl.com/docs',
    baseUrl: 'https://api.deepl.com/v2',
    pricing: { model: 'freemium', description: 'Free: 500k characters/month', tiers: [] },
    features: ['Text translation', 'Document translation', 'Glossaries', '30+ languages', 'Formality control'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 185,
    uptime30d: 99.95,
    uptime90d: 99.93,
    isVerified: true,
  },
  {
    slug: 'google-translate',
    name: 'Google Cloud Translation',
    description: 'Translate text and HTML between 100+ languages using Neural Machine Translation.',
    category: 'translation',
    tags: ['translation', 'google', 'nlp', 'multilingual', '100-languages'],
    logoUrl: 'https://logo.clearbit.com/cloud.google.com',
    websiteUrl: 'https://cloud.google.com/translate',
    docsUrl: 'https://cloud.google.com/translate/docs',
    baseUrl: 'https://translation.googleapis.com/language/translate/v2',
    pricing: { model: 'usage', description: '$20 per 1M characters', tiers: [] },
    features: ['100+ languages', 'HTML translation', 'Language detection', 'Glossaries', 'Batch translation'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 145,
    uptime30d: 99.98,
    uptime90d: 99.97,
    isVerified: true,
  },

  // ======== E-COMMERCE ========
  {
    slug: 'shopify',
    name: 'Shopify Admin API',
    description: 'Build apps for Shopify merchants. Access orders, products, customers, and checkout.',
    category: 'ecommerce',
    tags: ['ecommerce', 'shopify', 'orders', 'products', 'graphql'],
    logoUrl: 'https://logo.clearbit.com/shopify.com',
    websiteUrl: 'https://shopify.dev',
    docsUrl: 'https://shopify.dev/docs/api',
    baseUrl: 'https://YOUR_STORE.myshopify.com/admin/api/2024-01',
    pricing: { model: 'free', description: 'Free with Shopify partner account', tiers: [] },
    features: ['Products & inventory', 'Orders management', 'Customer data', 'GraphQL & REST', 'Webhooks', 'Storefront API'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 155,
    uptime30d: 99.98,
    uptime90d: 99.97,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'woocommerce',
    name: 'WooCommerce REST API',
    description: 'Interact with WooCommerce data — products, orders, customers, and reports — via REST API.',
    category: 'ecommerce',
    tags: ['ecommerce', 'wordpress', 'woocommerce', 'rest', 'orders'],
    logoUrl: 'https://logo.clearbit.com/woocommerce.com',
    websiteUrl: 'https://woocommerce.com',
    docsUrl: 'https://woocommerce.github.io/woocommerce-rest-api-docs',
    baseUrl: 'https://YOUR_STORE.com/wp-json/wc/v3',
    pricing: { model: 'free', description: 'Free (self-hosted)', tiers: [] },
    features: ['Products', 'Orders', 'Customers', 'Coupons', 'Reports', 'Webhooks'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 280,
    uptime30d: 99.80,
    uptime90d: 99.76,
    isVerified: false,
  },

  // ======== DEV TOOLS ========
  {
    slug: 'github-api',
    name: 'GitHub API',
    description: 'Build integrations with GitHub. Access repositories, issues, pull requests, and more.',
    category: 'devtools',
    tags: ['github', 'git', 'repositories', 'ci', 'collaboration'],
    logoUrl: 'https://logo.clearbit.com/github.com',
    websiteUrl: 'https://github.com',
    docsUrl: 'https://docs.github.com/en/rest',
    baseUrl: 'https://api.github.com',
    pricing: { model: 'freemium', description: 'Free: 5,000 requests/hour', tiers: [] },
    features: ['Repos & code', 'Issues & PRs', 'Actions', 'Packages', 'GraphQL API', 'Webhooks'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 88,
    uptime30d: 99.97,
    uptime90d: 99.95,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'gitlab-api',
    name: 'GitLab API',
    description: 'Comprehensive DevOps platform API. Manage CI/CD, repositories, merge requests, and deployments.',
    category: 'devtools',
    tags: ['gitlab', 'git', 'ci-cd', 'devops'],
    logoUrl: 'https://logo.clearbit.com/gitlab.com',
    websiteUrl: 'https://gitlab.com',
    docsUrl: 'https://docs.gitlab.com/ee/api',
    baseUrl: 'https://gitlab.com/api/v4',
    pricing: { model: 'freemium', description: 'Free tier available', tiers: [] },
    features: ['Repository management', 'CI/CD pipelines', 'Container registry', 'Security scanning', 'Merge requests'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 105,
    uptime30d: 99.93,
    uptime90d: 99.90,
    isVerified: true,
  },
  {
    slug: 'vercel',
    name: 'Vercel API',
    description: 'Programmatically manage deployments, domains, projects, and serverless functions on Vercel.',
    category: 'devtools',
    tags: ['deployment', 'serverless', 'cdn', 'edge', 'next.js'],
    logoUrl: 'https://logo.clearbit.com/vercel.com',
    websiteUrl: 'https://vercel.com',
    docsUrl: 'https://vercel.com/docs/rest-api',
    baseUrl: 'https://api.vercel.com',
    pricing: { model: 'freemium', description: 'Free tier: 100GB bandwidth', tiers: [] },
    features: ['Deployments', 'Domains', 'Edge functions', 'Analytics', 'Preview URLs', 'Webhooks'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 62,
    uptime30d: 99.99,
    uptime90d: 99.98,
    isVerified: true,
    isFeatured: true,
  },
  {
    slug: 'netlify',
    name: 'Netlify API',
    description: 'Build, deploy, and scale web applications with Netlify\'s powerful developer platform.',
    category: 'devtools',
    tags: ['deployment', 'jamstack', 'serverless', 'functions'],
    logoUrl: 'https://logo.clearbit.com/netlify.com',
    websiteUrl: 'https://netlify.com',
    docsUrl: 'https://docs.netlify.com/api/get-started',
    baseUrl: 'https://api.netlify.com/api/v1',
    pricing: { model: 'freemium', description: 'Free: 100GB/month bandwidth', tiers: [] },
    features: ['Deployments', 'Functions', 'Forms', 'Identity', 'Analytics', 'Build plugins'],
    currentStatus: 'OPERATIONAL',
    avgLatency: 78,
    uptime30d: 99.97,
    uptime90d: 99.96,
    isVerified: true,
  },
]

// Sample reviews for top APIs
const SAMPLE_REVIEWS = [
  { slug: 'stripe', rating: 5, title: 'The gold standard for payments', body: 'Stripe has the best developer experience of any payment API. The documentation is excellent, the SDKs are well-maintained, and the dashboard is intuitive. Been using it for 4 years across multiple projects.' },
  { slug: 'stripe', rating: 4, title: 'Excellent but can be pricey', body: 'Amazing API, superb docs, and great reliability. Pricing adds up quickly at scale but the quality justifies it for most use cases.' },
  { slug: 'auth0', rating: 5, title: 'Solved all our auth headaches', body: 'We switched from a custom auth solution to Auth0 and never looked back. The MFA, social login, and SSO support are all first-class.' },
  { slug: 'clerk', rating: 5, title: 'Best auth for Next.js', body: 'Clerk is incredible for Next.js projects. The drop-in components look great, the docs are comprehensive, and setup takes minutes.' },
  { slug: 'resend', rating: 5, title: 'Perfect email API for devs', body: 'Finally an email API designed for developers. The React Email integration is genius and deliverability has been excellent.' },
  { slug: 'openai', rating: 4, title: 'Powerful but rate limits are frustrating', body: 'The API is powerful and well-documented. Rate limits on the free/lower tiers can be frustrating during development, but production performance is solid.' },
  { slug: 'groq', rating: 5, title: 'Insanely fast inference', body: 'Groq is genuinely transformative for latency-sensitive AI features. Getting 500 tokens/second from LLaMA 3 is mind-blowing. Free tier is generous.' },
  { slug: 'google-gemini', rating: 4, title: 'Great free tier, solid performance', body: 'Gemini 1.5 Flash is excellent for price/performance. The 1M token context window is genuinely useful. Python SDK could be improved.' },
  { slug: 'supabase', rating: 5, title: 'Firebase killer for Postgres lovers', body: 'Supabase gives you everything Firebase has but with the power of Postgres underneath. The Row Level Security is brilliant.' },
  { slug: 'github-api', rating: 5, title: 'Rock solid, essential API', body: 'The GitHub API is comprehensive, well-documented, and reliable. The GraphQL API is particularly powerful for complex queries.' },
  { slug: 'mistral', rating: 5, title: 'Best price-performance LLM', body: 'Mistral Large rivals GPT-4 at a fraction of the cost. Codestral for code tasks is exceptional. The team ships fast.' },
  { slug: 'elevenlabs', rating: 5, title: 'Voices sound genuinely human', body: 'ElevenLabs voice cloning quality is unmatched. Used it for a podcast automation tool and the output was indistinguishable from real voices. Latency is the only gripe.' },
  { slug: 'sentry', rating: 5, title: 'Caught bugs before users reported them', body: 'Sentry has saved us countless times. The AI-suggested fixes and performance monitoring are worth the subscription alone. Session replay is invaluable for debugging.' },
  { slug: 'discord-api', rating: 4, title: 'Powerful but docs could be better', body: 'Discord API is feature-rich and the slash commands system is clean. Documentation has gaps but the community fills them in. Rate limits are reasonable for bots.' },
  { slug: 'shopify', rating: 5, title: 'Best e-commerce API ecosystem', body: "Shopify's GraphQL Admin API is a joy to work with. The Storefront API for headless commerce is powerful. Great webhooks, excellent documentation, strong partner ecosystem." },
  { slug: 'plaid', rating: 4, title: 'Reliable but expensive at scale', body: 'Plaid is the clear winner for bank connectivity. Link UI converts well, transaction data is clean, and the identity verification is solid. Pricing becomes painful at scale.' },
  { slug: 'upstash', rating: 5, title: 'Serverless Redis done right', body: 'Upstash has replaced Elasticache for most of our edge use cases. Zero-cost idle is a game changer. The REST API for edge environments is the killer feature.' },
  { slug: 'deepl', rating: 5, title: 'Noticeably better translations', body: 'Side-by-side tests with Google Translate show DeepL winning every time for European languages. The formality control feature is uniquely useful for B2B products.' },
]

async function main() {
  console.log('🌱 Starting seed...')

  // Create a seed user for reviews
  const seedUser = await prisma.user.upsert({
    where: { email: 'seed@apiverse.dev' },
    update: {},
    create: {
      email: 'seed@apiverse.dev',
      name: 'APIverse Team',
      emailVerified: new Date(),
    },
  })

  console.log(`✅ Created seed user: ${seedUser.email}`)

  // Seed APIs
  const createdApis = {}

  for (const apiData of APIS) {
    const { currentStatus, avgLatency, uptime30d, uptime90d, isFeatured, isVerified, ...rest } = apiData

    const api = await prisma.api.upsert({
      where: { slug: apiData.slug },
      update: {
        currentStatus,
        avgLatency,
        uptime30d,
        uptime90d,
        isFeatured: isFeatured ?? false,
        isVerified: isVerified ?? false,
        ...rest,
      },
      create: {
        currentStatus,
        avgLatency,
        uptime30d,
        uptime90d,
        isFeatured: isFeatured ?? false,
        isVerified: isVerified ?? false,
        ...rest,
      },
    })

    createdApis[api.slug] = api

    // Seed health logs for each API
    const statuses = currentStatus === 'OPERATIONAL'
      ? ['OPERATIONAL', 'OPERATIONAL', 'OPERATIONAL', 'OPERATIONAL', 'OPERATIONAL', 'DEGRADED']
      : currentStatus === 'DEGRADED'
        ? ['OPERATIONAL', 'DEGRADED', 'DEGRADED', 'OPERATIONAL', 'DEGRADED']
        : ['DOWN', 'DOWN', 'DEGRADED', 'OPERATIONAL']

    for (let i = 0; i < 12; i++) {
      const statusIdx = Math.floor(Math.random() * statuses.length)
      const status = statuses[statusIdx]
      const baseLatency = avgLatency || 100
      const jitter = Math.floor(Math.random() * baseLatency * 0.4) - baseLatency * 0.2

      await prisma.healthLog.create({
        data: {
          apiId: api.id,
          status,
          latency: Math.max(10, baseLatency + jitter),
          statusCode: status === 'DOWN' ? 503 : status === 'DEGRADED' ? 429 : 200,
          checkedAt: new Date(Date.now() - i * 5 * 60 * 1000), // every 5 minutes back
        },
      }).catch(() => {}) // Ignore duplicates
    }
  }

  console.log(`✅ Seeded ${APIS.length} APIs with health logs`)

  // Seed reviews
  for (const review of SAMPLE_REVIEWS) {
    const api = createdApis[review.slug]
    if (!api) continue

    await prisma.review.upsert({
      where: { apiId_userId: { apiId: api.id, userId: seedUser.id } },
      update: {},
      create: {
        apiId: api.id,
        userId: seedUser.id,
        rating: review.rating,
        title: review.title,
        body: review.body,
        isVerified: true,
      },
    })
  }

  console.log(`✅ Seeded ${SAMPLE_REVIEWS.length} reviews`)

  // Seed changelogs for select APIs
  const changelogEntries = [
    { slug: 'stripe', version: '2024-12-18', title: 'New: Payment Links v2 with advanced customization', severity: 'MINOR', isBreaking: false },
    { slug: 'openai', version: 'gpt-4o-2024-11-20', title: 'GPT-4o fine-tuning now available for all users', severity: 'MINOR', isBreaking: false },
    { slug: 'openai', version: '2024-08-06', title: 'Structured outputs: enforce JSON schemas in responses', severity: 'MINOR', isBreaking: false },
    { slug: 'auth0', version: '2.0.0', title: 'Next.js SDK v4: Breaking changes to session handling', severity: 'BREAKING', isBreaking: true },
    { slug: 'supabase', version: '2.39.0', title: 'pgvector 0.7.0 upgrade — improved HNSW performance', severity: 'PATCH', isBreaking: false },
    { slug: 'vercel', version: 'v4', title: 'AI SDK 4.0: New streaming UI components', severity: 'MAJOR', isBreaking: false },
    { slug: 'mistral', version: '2024-11', title: 'Mistral Large 2 released with 128k context window', severity: 'MINOR', isBreaking: false },
    { slug: 'elevenlabs', version: 'v2', title: 'Turbo v2.5 model: 75ms latency, 32 languages', severity: 'MINOR', isBreaking: false },
    { slug: 'discord-api', version: 'v10', title: 'Breaking: Legacy username system fully deprecated', severity: 'BREAKING', isBreaking: true },
    { slug: 'shopify', version: '2024-10', title: 'New: Combined Listings API for product variants', severity: 'MINOR', isBreaking: false },
    { slug: 'sentry', version: '24.10', title: 'Autofix AI: Automated root cause analysis for errors', severity: 'MINOR', isBreaking: false },
    { slug: 'upstash', version: '2024-09', title: 'Vector DB: Semantic search now GA', severity: 'MINOR', isBreaking: false },
    { slug: 'twitter-api', version: 'v2', title: 'Breaking: Free tier limited to 1,500 tweets/month', severity: 'BREAKING', isBreaking: true },
  ]

  for (const entry of changelogEntries) {
    const api = createdApis[entry.slug]
    if (!api) continue

    await prisma.changelog.create({
      data: {
        apiId: api.id,
        version: entry.version,
        title: entry.title,
        description: `${entry.title}. See the full changelog for details.`,
        severity: entry.severity,
        isBreaking: entry.isBreaking,
        publishedAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000),
      },
    }).catch(() => {})
  }

  console.log(`✅ Seeded ${changelogEntries.length} changelog entries`)

  console.log('\n🎉 Seed complete!')
  console.log(`   APIs: ${APIS.length}`)
  console.log(`   Reviews: ${SAMPLE_REVIEWS.length}`)
  console.log(`   Changelogs: ${changelogEntries.length}`)
}

main()
  .catch((e) => {
    console.error('Seed failed:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
