'use client'

import { useState, useEffect } from 'react'
import { motion, AnimatePresence, Reorder, useDragControls } from 'framer-motion'
import styles from './compose.module.css'

const DEFAULT_STEPS = [
  { id: 's1', icon: '📧', api: 'Resend',   action: 'Verify Email',       desc: 'Validate email format and deliverability',  color: '#6366f1' },
  { id: 's2', icon: '💳', api: 'Stripe',   action: 'Create Customer',    desc: 'Register customer in payment system',        color: '#10b981' },
  { id: 's3', icon: '✉️', api: 'SendGrid', action: 'Send Welcome Email', desc: 'Deliver onboarding email to new user',       color: '#f59e0b' },
  { id: 's4', icon: '📊', api: 'Mixpanel', action: 'Log to Analytics',   desc: 'Track signup event with user properties',    color: '#8b5cf6' },
]

const API_PALETTE = [
  { icon: '🔐', api: 'Auth0',      action: 'Authenticate User',  desc: 'Verify identity and permissions',      color: '#6366f1' },
  { icon: '💳', api: 'Stripe',     action: 'Create Payment',     desc: 'Process payment transaction',          color: '#10b981' },
  { icon: '📧', api: 'Resend',     action: 'Send Email',         desc: 'Deliver transactional email',          color: '#6366f1' },
  { icon: '✉️', api: 'SendGrid',   action: 'Send Marketing',     desc: 'Deliver marketing email',              color: '#f59e0b' },
  { icon: '🗄️', api: 'Supabase',   action: 'Save to Database',   desc: 'Persist data in Postgres',             color: '#06b6d4' },
  { icon: '🔍', api: 'Algolia',    action: 'Search Records',     desc: 'Query indexed data',                   color: '#10b981' },
  { icon: '📊', api: 'Mixpanel',   action: 'Track Event',        desc: 'Log analytics event',                  color: '#8b5cf6' },
  { icon: '🤖', api: 'OpenAI',     action: 'AI Completion',      desc: 'Generate text with GPT-4',            color: '#f59e0b' },
  { icon: '☁️', api: 'Cloudinary', action: 'Upload Media',       desc: 'Store and transform images/video',     color: '#3b82f6' },
  { icon: '📨', api: 'Twilio',     action: 'Send SMS',           desc: 'Deliver text message to user',         color: '#ef4444' },
  { icon: '🦔', api: 'PostHog',    action: 'Log Analytics',      desc: 'Record usage event',                   color: '#8b5cf6' },
  { icon: '🔔', api: 'Pusher',     action: 'Push Notification',  desc: 'Send real-time push event',            color: '#f59e0b' },
]

const GENERATED_STEPS_MAP = {
  'user signup': [
    { icon: '📧', api: 'Resend',   action: 'Verify Email',       desc: 'Validate email format and deliverability',  color: '#6366f1' },
    { icon: '💳', api: 'Stripe',   action: 'Create Customer',    desc: 'Register customer in payment system',        color: '#10b981' },
    { icon: '✉️', api: 'SendGrid', action: 'Send Welcome Email', desc: 'Deliver onboarding email to new user',       color: '#f59e0b' },
    { icon: '📊', api: 'Mixpanel', action: 'Log to Analytics',   desc: 'Track signup event with user properties',    color: '#8b5cf6' },
  ],
  'checkout': [
    { icon: '🔐', api: 'Auth0',    action: 'Verify Session',        desc: 'Ensure user is authenticated',               color: '#6366f1' },
    { icon: '💳', api: 'Stripe',   action: 'Create Payment Intent', desc: 'Initialize payment session',                 color: '#10b981' },
    { icon: '🗄️', api: 'Supabase', action: 'Create Order Record',   desc: 'Persist order in database',                  color: '#06b6d4' },
    { icon: '✉️', api: 'Resend',   action: 'Send Receipt',          desc: 'Email payment confirmation to user',          color: '#f59e0b' },
    { icon: '🦔', api: 'PostHog',  action: 'Track Conversion',      desc: 'Record purchase event for analytics',         color: '#8b5cf6' },
  ],
  'default': [
    { icon: '🔐', api: 'Auth0',   action: 'Authenticate User', desc: 'Verify user identity and permissions',     color: '#6366f1' },
    { icon: '🔍', api: 'Algolia', action: 'Search Records',    desc: 'Query indexed data with AI ranking',       color: '#10b981' },
    { icon: '🤖', api: 'OpenAI',  action: 'AI Processing',     desc: 'Analyze and transform data with GPT-4',    color: '#f59e0b' },
    { icon: '📊', api: 'PostHog', action: 'Log Analytics',     desc: 'Record workflow execution event',          color: '#8b5cf6' },
  ],
}

const GENERATED_CODE = (steps) => `import axios from 'axios';

// APIverse Composition Pipeline
// Generated by AI Studio

async function executePipeline(input) {
  const results = {};

${steps.map((step, i) => `  // Step ${i + 1}: ${step.action} via ${step.api}
  results.step${i + 1} = await ${step.api.replace(/\s/g, '').toLowerCase()}Client.${step.action.replace(/\s/g, '_').toLowerCase()}({
    ...input,
    prev: ${i === 0 ? 'null' : `results.step${i}`}
  });
  console.log('✓ ${step.action} completed');
`).join('\n')}
  return results;
}

// Execute the pipeline
executePipeline({ userId: 'usr_abc123', email: 'dev@example.com' })
  .then(result => console.log('Pipeline complete:', result))
  .catch(err => console.error('Pipeline failed:', err));`

function PipelineStep({ step, index, total, onDelete }) {
  const dragControls = useDragControls()

  return (
    <Reorder.Item
      value={step}
      id={step.id}
      as="div"
      className={styles.stepWrap}
      dragListener={false}
      dragControls={dragControls}
    >
      <div className={styles.step} style={{ borderColor: step.color + '40' }}>
        <div className={styles.dragHandle} onPointerDown={e => dragControls.start(e)}>⠿</div>
        <div className={styles.stepNum} style={{ background: step.color + '20', color: step.color }}>
          {index + 1}
        </div>
        <div className={styles.stepIcon}>{step.icon}</div>
        <div className={styles.stepInfo}>
          <div className={styles.stepApi} style={{ color: step.color }}>{step.api}</div>
          <div className={styles.stepAction}>{step.action}</div>
          <div className={styles.stepDesc}>{step.desc}</div>
        </div>
        <div className={styles.stepStatus}>
          <span className={styles.statusDot} style={{ background: step.color }} />
        </div>
        <button className={styles.deleteBtn} onClick={() => onDelete(step.id)}>×</button>
      </div>
      {index < total - 1 && (
        <div className={styles.connector}>
          <div className={styles.connectorLine} style={{ background: step.color + '40' }} />
          <div className={styles.connectorArrow} style={{ color: step.color }}>↓</div>
        </div>
      )}
    </Reorder.Item>
  )
}

export default function ComposePage() {
  const [workflow, setWorkflow] = useState('')
  const [generating, setGenerating] = useState(false)
  const [steps, setSteps] = useState(DEFAULT_STEPS)
  const [generated, setGenerated] = useState(false)
  const [copied, setCopied] = useState(false)
  const [showCode, setShowCode] = useState(false)
  const [apiCount, setApiCount] = useState(null)
  const [showPicker, setShowPicker] = useState(false)

  useEffect(() => {
    fetch('/api/stats')
      .then(r => r.json())
      .then(d => setApiCount(d.total || null))
      .catch(() => {})
  }, [])

  function addStep(api) {
    setSteps(prev => [...prev, { ...api, id: `step-${Date.now()}` }])
    setShowPicker(false)
  }

  function deleteStep(id) {
    setSteps(prev => prev.filter(s => s.id !== id))
  }

  async function handleGenerate() {
    if (!workflow.trim()) return
    setGenerating(true)
    setGenerated(false)

    try {
      const res = await fetch('/api/compose', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ description: workflow }),
      })
      const data = await res.json()

      if (data.steps?.length) {
        setSteps(data.steps.map((s, i) => ({ id: `g-${Date.now()}-${i}`, ...s })))
      } else {
        const lc = workflow.toLowerCase()
        let newSteps = GENERATED_STEPS_MAP['default']
        if (lc.includes('signup') || lc.includes('register') || lc.includes('onboard')) {
          newSteps = GENERATED_STEPS_MAP['user signup']
        } else if (lc.includes('checkout') || lc.includes('payment') || lc.includes('purchase')) {
          newSteps = GENERATED_STEPS_MAP['checkout']
        }
        setSteps(newSteps.map((s, i) => ({ id: `g-${Date.now()}-${i}`, ...s })))
      }
    } catch {
      const lc = workflow.toLowerCase()
      let newSteps = GENERATED_STEPS_MAP['default']
      if (lc.includes('signup') || lc.includes('register') || lc.includes('onboard')) {
        newSteps = GENERATED_STEPS_MAP['user signup']
      } else if (lc.includes('checkout') || lc.includes('payment') || lc.includes('purchase')) {
        newSteps = GENERATED_STEPS_MAP['checkout']
      }
      setSteps(newSteps.map((s, i) => ({ id: `g-${Date.now()}-${i}`, ...s })))
    } finally {
      setGenerating(false)
      setGenerated(true)
      setShowCode(true)
    }
  }

  function copyCode() {
    navigator.clipboard.writeText(GENERATED_CODE(steps))
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const codeStr = GENERATED_CODE(steps)

  return (
    <div className={styles.page}>

      {/* Canvas Live Banner */}
      <div className={styles.comingSoonBanner}>
        <span className={styles.bannerIcon}>✦</span>
        <span className={styles.bannerText}>
          <strong>Visual Canvas</strong> — drag the handle ⠿ to reorder steps, click <strong>+ Add Step</strong> to add more.
        </span>
      </div>

      <div className={styles.container}>
        {/* Hero */}
        <motion.div
          className={styles.hero}
          initial={{ opacity: 0, y: 24 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <div className={styles.heroLabel}>
            <span>✦</span> AI-Powered
          </div>
          <h1 className={styles.heroTitle}>
            API Composition <span className={styles.heroGradient}>Studio</span>
          </h1>
          <p className={styles.heroSubtitle}>
            Chain APIs together with AI. Describe your workflow in plain English and get a production-ready pipeline instantly.
          </p>
        </motion.div>

        {/* Main Layout */}
        <div className={styles.mainLayout}>
          {/* Left: Describe */}
          <motion.div
            className={styles.leftPanel}
            initial={{ opacity: 0, x: -24 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            <div className={styles.panel}>
              <div className={styles.panelHeader}>
                <span className={styles.panelTitle}>Describe your workflow</span>
                <span className={styles.aiBadge}>✦ AI</span>
              </div>

              <div className={styles.panelBody}>
                <textarea
                  className={styles.workflowInput}
                  placeholder={`Example: "When a user signs up, verify their email, create a Stripe customer, send a welcome email, and log the event to analytics."`}
                  value={workflow}
                  onChange={e => setWorkflow(e.target.value)}
                  rows={6}
                />

                <div className={styles.promptSuggestions}>
                  <span className={styles.suggestLabel}>Try:</span>
                  {['User signup flow', 'Checkout pipeline', 'Auth + search + AI'].map(s => (
                    <button
                      key={s}
                      className={styles.suggestion}
                      onClick={() => setWorkflow(s)}
                    >
                      {s}
                    </button>
                  ))}
                </div>

                <button
                  className={styles.generateBtn}
                  onClick={handleGenerate}
                  disabled={generating || !workflow.trim()}
                >
                  {generating ? (
                    <>
                      <span className={styles.spinner} />
                      Generating Pipeline...
                    </>
                  ) : (
                    <>
                      <span>✦</span>
                      Generate Pipeline
                    </>
                  )}
                </button>

                {generated && (
                  <motion.div
                    className={styles.successNote}
                    initial={{ opacity: 0, scale: 0.95 }}
                    animate={{ opacity: 1, scale: 1 }}
                  >
                    ✅ Pipeline generated with {steps.length} steps
                  </motion.div>
                )}

              </div>

              <div className={styles.panelFooter}>
                <div className={styles.footerStat}>
                  <span className={styles.footerStatNum}>{apiCount ?? '—'}</span>
                  <span className={styles.footerStatLabel}>Supported APIs</span>
                </div>
                <div className={styles.footerStat}>
                  <span className={styles.footerStatNum}>100+</span>
                  <span className={styles.footerStatLabel}>Templates</span>
                </div>
                <div className={styles.footerStat}>
                  <span className={styles.footerStatNum}>3s</span>
                  <span className={styles.footerStatLabel}>Avg Generate Time</span>
                </div>
              </div>
            </div>
          </motion.div>

          {/* Right: Visual Canvas */}
          <motion.div
            className={styles.rightPanel}
            initial={{ opacity: 0, x: 24 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.5, delay: 0.15 }}
          >
            <div className={styles.panel}>
              <div className={styles.panelHeader}>
                <span className={styles.panelTitle}>Visual Canvas</span>
                {generated && (
                  <span className={styles.generatedBadge}>✓ AI Generated</span>
                )}
              </div>

              <div className={styles.pipelineBody}>
                <Reorder.Group
                  axis="y"
                  values={steps}
                  onReorder={setSteps}
                  as="div"
                  className={styles.reorderGroup}
                >
                  {steps.map((step, i) => (
                    <PipelineStep
                      key={step.id}
                      step={step}
                      index={i}
                      total={steps.length}
                      onDelete={deleteStep}
                    />
                  ))}
                </Reorder.Group>

                {showPicker ? (
                  <motion.div
                    className={styles.picker}
                    initial={{ opacity: 0, y: -8 }}
                    animate={{ opacity: 1, y: 0 }}
                  >
                    <div className={styles.pickerHeader}>
                      <span>Pick an API</span>
                      <button onClick={() => setShowPicker(false)}>✕</button>
                    </div>
                    <div className={styles.pickerGrid}>
                      {API_PALETTE.map(api => (
                        <button
                          key={api.api + api.action}
                          className={styles.pickerItem}
                          onClick={() => addStep(api)}
                        >
                          <span>{api.icon}</span>
                          <span>{api.api}</span>
                          <span className={styles.pickerItemDesc}>{api.action}</span>
                        </button>
                      ))}
                    </div>
                  </motion.div>
                ) : (
                  <button className={styles.addStepBtn} onClick={() => setShowPicker(true)}>
                    + Add Step
                  </button>
                )}

                {generating && (
                  <motion.div
                    className={styles.generatingOverlay}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                  >
                    <div className={styles.generatingSpinner} />
                    <span>AI is analyzing your workflow...</span>
                  </motion.div>
                )}
              </div>
            </div>
          </motion.div>
        </div>

        {/* Generated Code */}
        <AnimatePresence>
          {showCode && (
            <motion.div
              className={styles.codeSection}
              initial={{ opacity: 0, y: 24 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -12 }}
              transition={{ duration: 0.4 }}
            >
              <div className={styles.codeSectionHeader}>
                <div>
                  <h2 className={styles.codeSectionTitle}>Generated Code</h2>
                  <p className={styles.codeSectionSub}>Production-ready JavaScript pipeline. Copy and customize.</p>
                </div>
                <button className={styles.copyBtn} onClick={copyCode}>
                  {copied ? '✓ Copied!' : 'Copy Code'}
                </button>
              </div>

              <div className={styles.codeBlock}>
                <div className={styles.codeHeader}>
                  <div className={styles.trafficLights}>
                    <span className={styles.dot} style={{ background: '#ef4444' }} />
                    <span className={styles.dot} style={{ background: '#f59e0b' }} />
                    <span className={styles.dot} style={{ background: '#10b981' }} />
                  </div>
                  <span className={styles.codeFile}>pipeline.js</span>
                </div>
                <pre className={styles.codePre}>
                  <code>{codeStr}</code>
                </pre>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  )
}
